spring:
  application:
    name: backend
  profiles:
    active: prod
    include: secrets
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5 
      connection-timeout: 30000
      idle-timeout: 600000         # 10분
      max-lifetime: 1800000        # 30분
      leak-detection-threshold: 120000  # 연결 누수 감지
      validation-timeout: 5000     # 연결 검증 타임아웃
  data:
    mongodb:
      uri: ${mongodb.uri}
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password:}
      timeout: 2000ms
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch-size: 25                    # 배치 처리 크기
        order-inserts: true                 # INSERT 순서 최적화
        order-updates: true                 # UPDATE 순서 최적화
        batch-versioned-data: true          # 버전 데이터 배치 처리
        connection:
          provider-disables-autocommit: false  # JdbcTemplate 호환성 
        # SQL 줄바꿈과 포맷팅을 위한 설정
        type:
          sql-trace: true
    show-sql: true
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  jackson:
    parser:
      allow-non-numeric-numbers: true  # NaN, Infinity 등 비표준 숫자 허용

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# AI 프롬프트 설정
ai:
  prompts:
    backtest-report:
      template-file: "classpath:templates/backtest-report-prompt.md"
    portfolio-optimization:
      template-file: "classpath:templates/portfolio-optimization-prompt.md"

logging:
  level:
    com:
      stockone19: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE              # SQL 파라미터 바인딩 추적
        SQL: DEBUG                           # SQL 로깅 활성화
      springframework:
        web: DEBUG                           # 웹 레이어 디버깅
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    