spring:
  application:
    name: backend
  profiles:
    active: prod
    include: secrets
  datasource:
    hikari:
      maximum-pool-size: 20        # 연결 풀 크기 증가
      minimum-idle: 5              # 최소 유휴 연결 수 증가
      connection-timeout: 30000    # 30초로 증가
      idle-timeout: 600000         # 10분
      max-lifetime: 1800000        # 30분
      leak-detection-threshold: 60000  # 연결 누수 감지 (1분)
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25                    # 배치 처리 크기
        order_inserts: true                 # INSERT 순서 최적화
        order_updates: true                 # UPDATE 순서 최적화
        batch_versioned_data: true          # 버전 데이터 배치 처리
        connection:
          provider_disables_autocommit: false  # JdbcTemplate 호환성
  data:
    mongodb:
      uri: ${mongodb.uri}
      # MongoDB 연결 타임아웃 설정
      options:
        connect-timeout: 10000
        socket-timeout: 30000
        server-selection-timeout: 5000
        max-connection-idle-time: 60000
        max-connection-life-time: 600000
        max-connections-per-host: 10
        min-connections-per-host: 2
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password:}
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.stockone19: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
