spring:
  application:
    name: backend
  profiles:
    active: prod
    include: secrets
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5 
      connection-timeout: 30000
      idle-timeout: 600000         # 10분
      max-lifetime: 1800000        # 30분
      leak-detection-threshold: 120000  # 연결 누수 감지
      max-active: 20               # 최대 활성 연결 수
      validation-timeout: 5000     # 연결 검증 타임아웃
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25                    # 배치 처리 크기
        order_inserts: true                 # INSERT 순서 최적화
        order_updates: true                 # UPDATE 순서 최적화
        batch_versioned_data: true          # 버전 데이터 배치 처리
        connection:
          provider_disables_autocommit: false  # JdbcTemplate 호환성
  data:
    mongodb:
      uri: ${mongodb.uri}
      # MongoDB 트랜잭션 관련 설정
      transaction:
        enabled: false
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password:}
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.stockone19: INFO
    # MongoDB 쿼리 로그 활성화
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.query: DEBUG
    org.springframework.data.mongodb: DEBUG
    # MongoDB 드라이버 로그 (선택사항)
    org.mongodb.driver: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    